import { z } from "zod";
import Handlebars from "handlebars";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname } from "path";
import type { ToolDef, ToolContext, ExecuteResult } from "../tool.js";

const Parameters = z.object({
  template: z.string().describe("Template name (e.g., 'brd', 'user-story') or 'list' to show available"),
  data: z.record(z.string(), z.unknown()).optional().describe("Template variables to fill in"),
  outputPath: z.string().optional().describe("Output file path"),
});

const BUILTIN_TEMPLATES: Record<string, { name: string; description: string }> = {
  "brd": { name: "Business Requirements Document", description: "Comprehensive BRD template" },
  "frd": { name: "Functional Requirements Document", description: "Detailed functional requirements" },
  "user-story": { name: "User Story", description: "Agile user story template" },
  "acceptance-criteria": { name: "Acceptance Criteria", description: "Acceptance criteria template" },
  "meeting-notes": { name: "Meeting Notes", description: "Structured meeting notes" },
  "raci-matrix": { name: "RACI Matrix", description: "Responsibility assignment matrix" },
  "swot-analysis": { name: "SWOT Analysis", description: "Strategic planning template" },
  "status-report": { name: "Status Report", description: "Project status report" },
};

const templateTool: ToolDef<z.infer<typeof Parameters>> = {
  id: "template",
  description: "Load and fill document templates. Use 'list' to see available templates.",
  parameters: Parameters,

  async execute(args, ctx: ToolContext): Promise<ExecuteResult> {
    if (args.template === "list") {
      const list = Object.entries(BUILTIN_TEMPLATES)
        .map(([key, t]) => `  - ${key}: ${t.name} — ${t.description}`)
        .join("\n");

      return {
        title: "Available templates",
        output: `Built-in templates:\n${list}\n\nUse: template <name> with data parameters to generate.`,
        metadata: { templates: Object.keys(BUILTIN_TEMPLATES) },
      };
    }

    const templateInfo = BUILTIN_TEMPLATES[args.template];
    if (!templateInfo) {
      return {
        title: "Template not found",
        output: `Template '${args.template}' not found. Use 'template list' to see available templates.`,
      };
    }

    const templateContent = getTemplateContent(args.template, templateInfo.name);
    const compiled = Handlebars.compile(templateContent);
    const data = args.data ?? {};
    const filled = compiled(data);

    const outDir = join(process.cwd(), "output");
    if (!existsSync(outDir)) {
      await mkdir(outDir, { recursive: true });
    }

    const outputPath = args.outputPath || join(outDir, `${args.template}-${Date.now()}.md`);
    const outDirPath = dirname(outputPath);
    if (!existsSync(outDirPath)) {
      await mkdir(outDirPath, { recursive: true });
    }

    await writeFile(outputPath, filled, "utf-8");

    return {
      title: `Generated ${templateInfo.name}`,
      output: `Template: ${args.template}\nSaved to: ${outputPath}\nVariables used: ${Object.keys(data).join(", ") || "none"}`,
      metadata: { template: args.template, path: outputPath },
    };
  },
};

function getTemplateContent(name: string, title: string): string {
  // Built-in template definitions (portable, no external files needed)
  const templates: Record<string, string> = {
    "brd": `# Business Requirements Document

**Project:** {{project}}
**Author:** {{author}}
**Date:** {{date}}
**Version:** {{version}}

---

## 1. Executive Summary

{{executiveSummary}}

## 2. Business Objectives

{{objectives}}

## 3. Scope

### In Scope
{{inScope}}

### Out of Scope
{{outOfScope}}

## 4. Stakeholders

| Stakeholder | Role | Responsibility |
|-------------|------|----------------|
{{#each stakeholders}}
| {{this.name}} | {{this.role}} | {{this.responsibility}} |
{{/each}}

## 5. Functional Requirements

{{#each functionalRequirements}}
### FR-{{@index}}: {{this.title}}
- **Description:** {{this.description}}
- **Priority:** {{this.priority}}
- **Acceptance Criteria:** {{this.acceptanceCriteria}}

{{/each}}

## 6. Non-Functional Requirements

{{#each nonFunctionalRequirements}}
### NFR-{{@index}}: {{this.title}}
- **Description:** {{this.description}}
- **Category:** {{this.category}}

{{/each}}

## 7. Assumptions

{{assumptions}}

## 8. Constraints

{{constraints}}

## 9. Risks

{{risks}}

---

*Document generated by bacli BA Agent*`,
    "user-story": `# User Story

**Title:** {{title}}
**Epic:** {{epic}}
**Priority:** {{priority}}
**Story Points:** {{points}}

---

## Description

As a **{{role}}**, I want **{{goal}}** so that **{{benefit}}**.

## Acceptance Criteria

{{#each acceptanceCriteria}}
- [ ] {{this}}
{{/each}}

## Technical Notes

{{technicalNotes}}

## Definition of Done

- [ ] Code reviewed
- [ ] Tested
- [ ] Documentation updated
- [ ] Acceptance criteria met`,
    "meeting-notes": `# Meeting Notes

**Meeting:** {{meetingTitle}}
**Date:** {{date}}
**Attendees:** {{attendees}}
**Duration:** {{duration}}

---

## Agenda

{{#each agenda}}
- {{this}}
{{/each}}

## Discussion Points

{{#each discussionPoints}}
### {{this.topic}}
{{this.notes}}

{{/each}}

## Action Items

| # | Action Item | Owner | Due Date |
|---|-------------|-------|----------|
{{#each actionItems}}
| {{@index}} | {{this.task}} | {{this.owner}} | {{this.dueDate}} |
{{/each}}

## Next Meeting

{{nextMeeting}}

---

*Notes generated by bacli BA Agent*`,
    "default": `# {{title}}

{{content}}
`,
  };

  return templates[name] || templates.default;
}

export default templateTool;
