import { z } from "zod";
import { writeFile, mkdir } from "fs/promises";
import { existsSync } from "fs";
import { join, dirname } from "path";
import type { ToolDef, ToolContext, ExecuteResult } from "../tool.js";

const Parameters = z.object({
  title: z.string().describe("Script name/title"),
  language: z.enum(["bash", "powershell", "python", "batch"]).describe("Script language"),
  description: z.string().describe("What the script should do"),
  content: z.string().describe("The actual script content/code"),
  outputPath: z.string().optional().describe("Output file path"),
});

const extensions: Record<string, string> = {
  bash: "sh",
  powershell: "ps1",
  python: "py",
  batch: "bat",
};

const shebangs: Record<string, string> = {
  bash: "#!/usr/bin/env bash",
  powershell: "#Requires -Version 5.1",
  python: "#!/usr/bin/env python3",
  batch: "@echo off",
};

const scriptGenTool: ToolDef<z.infer<typeof Parameters>> = {
  id: "scriptGen",
  description: "Generate shell scripts (Bash, PowerShell, Python, Batch) with shebangs and metadata headers.",
  parameters: Parameters,

  async execute(args, ctx: ToolContext): Promise<ExecuteResult> {
    const ext = extensions[args.language] || "sh";
    const sanitized = args.title.replace(/[<>:"/\\|?*]/g, "_");
    const outDir = join(process.cwd(), "output");
    if (!existsSync(outDir)) {
      await mkdir(outDir, { recursive: true });
    }

    const outputPath = args.outputPath || join(outDir, `${sanitized}.${ext}`);
    const outDirPath = dirname(outputPath);
    if (!existsSync(outDirPath)) {
      await mkdir(outDirPath, { recursive: true });
    }

    const header = [
      shebangs[args.language] || "",
      "",
      `# Script: ${args.title}`,
      `# Description: ${args.description}`,
      `# Generated by: bacli SysAdmin Agent`,
      `# Date: ${new Date().toISOString().split("T")[0]}`,
      "#",
      "# WARNING: Review this script before running in production",
      "#",
      "",
    ].join("\n");

    const fullScript = header + args.content;
    await writeFile(outputPath, fullScript, "utf-8");

    // Make executable on Unix
    if (args.language === "bash" || args.language === "python") {
      try {
        const { chmod } = await import("fs/promises");
        await chmod(outputPath, 0o755);
      } catch {}
    }

    return {
      title: `Generated ${args.language} script: ${args.title}`,
      output: [
        `Script saved to: ${outputPath}`,
        `Language: ${args.language}`,
        `Size: ${fullScript.length} bytes`,
        "",
        `Description: ${args.description}`,
        "",
        "⚠️ Review all scripts before executing them in production environments.",
      ].join("\n"),
      metadata: {
        path: outputPath,
        language: args.language,
        size: fullScript.length,
      },
    };
  },
};

export default scriptGenTool;
